export const featuredVideos = [
    {
      id: 1,
      channelIcon: "https://ca.slack-edge.com/TQ0UP44F8-UQ0UPEQB0-c4138922c921-512",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Mansur",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 11, 24, 10, 33, 30, 0),
      video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4", type: "video/mp4",  },
    },
    {
      id: 2,
      channelIcon: "",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Sonny",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 3, 15, 10, 33, 30, 0),
      video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", type: "video/mp4",  },
    },
    {
      id: 3,
      channelIcon: "https://ca.slack-edge.com/TQ0UP44F8-UPYNRRNRK-g9910871c159-512",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Won",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 11, 24, 10, 33, 30, 0),
      video: { src: "https://www.radiantmediaplayer.com/media/bbb-360p.mp4 ", type: "video/mp4",  },
    },
    {
      id: 4,
      channelIcon: "https://ca.slack-edge.com/TQ0UP44F8-UQ0UPEQB0-c4138922c921-512",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Mansur",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 3, 15, 10, 33, 30, 0),
      video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", type: "video/mp4",  },
    },  {
      id: 5,
      channelIcon: "",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Sonny",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 11, 24, 10, 33, 30, 0),
      video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4", type: "video/mp4",  },
    },
    {
      id: 6,
      channelIcon: "https://ca.slack-edge.com/TQ0UP44F8-UPYNRRNRK-g9910871c159-512",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Won",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 3, 15, 10, 33, 30, 0),
      video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", type: "video/mp4",  },
    },  {
      id: 7,
      channelIcon: "",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Mansur",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 11, 24, 10, 33, 30, 0),
      video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4", type: "video/mp4",  },
    },
    {
      id: 8,
      channelIcon: "https://ca.slack-edge.com/TQ0UP44F8-UQ0UPEQB0-c4138922c921-512",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Sonny",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 3, 15, 10, 33, 30, 0),
      video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", type: "video/mp4",  },
    },
    {
      id: 1,
      channelIcon: "https://ca.slack-edge.com/TQ0UP44F8-UQ0UPEQB0-c4138922c921-512",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Mansur",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 11, 24, 10, 33, 30, 0),
      video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4", type: "video/mp4",  },
    },
    {
      id: 2,
      channelIcon: "",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Sonny",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 3, 15, 10, 33, 30, 0),
      video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", type: "video/mp4",  },
    },
    {
      id: 3,
      channelIcon: "https://ca.slack-edge.com/TQ0UP44F8-UPYNRRNRK-g9910871c159-512",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Won",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 11, 24, 10, 33, 30, 0),
      video: { src: "https://www.radiantmediaplayer.com/media/bbb-360p.mp4 ", type: "video/mp4",  },
    },
    {
      id: 4,
      channelIcon: "https://ca.slack-edge.com/TQ0UP44F8-UQ0UPEQB0-c4138922c921-512",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Mansur",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 3, 15, 10, 33, 30, 0),
      video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", type: "video/mp4",  },
    },  {
      id: 5,
      channelIcon: "",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Sonny",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 11, 24, 10, 33, 30, 0),
      video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4", type: "video/mp4",  },
    },
    {
      id: 6,
      channelIcon: "https://ca.slack-edge.com/TQ0UP44F8-UPYNRRNRK-g9910871c159-512",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Won",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 3, 15, 10, 33, 30, 0),
      video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", type: "video/mp4",  },
    },  {
      id: 7,
      channelIcon: "",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Mansur",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 11, 24, 10, 33, 30, 0),
      video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4", type: "video/mp4",  },
    },
    {
      id: 8,
      channelIcon: "https://ca.slack-edge.com/TQ0UP44F8-UQ0UPEQB0-c4138922c921-512",
      channelName:"Fowl Behold Saw",
      title: "Waters Years",
      desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
      author: "Sonny",
      views: "27,548",
      time: "2 hours ago",
      date: new Date(2018, 3, 15, 10, 33, 30, 0),
      video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", type: "video/mp4",  },
    }
  ]

    export const regionVideos = [
      {
        id: 1,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "Waters Years",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Mansur",
        views: "27,548",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4", type: "video/mp4",  },
      },
      {
        id: 2,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "Waters Years",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Sonny",
        views: "27,548",
        time: "2 hours ago",
        date: new Date(2018, 3, 15, 10, 33, 30, 0),
        video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", type: "video/mp4",  },
      },
      {
        id: 3,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "Waters Years",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Won",
        views: "27,548",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        video: { src: "https://www.radiantmediaplayer.com/media/bbb-360p.mp4 ", type: "video/mp4",  },
      },
      {
        id: 4,
        channelIcon: "https://ca.slack-edge.com/TQ0UP44F8-UQ0UPEQB0-c4138922c921-512",
        channelName:"Fowl Behold Saw",
        title: "Waters Years",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Mansur",
        views: "27,548",
        time: "2 hours ago",
        date: new Date(2018, 3, 15, 10, 33, 30, 0),
        video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", type: "video/mp4",  },
      },  {
        id: 5,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "Waters Years",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Sonny",
        views: "27,548",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4", type: "video/mp4",  },
      },
      {
        id: 6,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "Waters Years",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Won",
        views: "27,548",
        time: "2 hours ago",
        date: new Date(2018, 3, 15, 10, 33, 30, 0),
        video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", type: "video/mp4",  },
      },  {
        id: 7,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "Waters Years",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Mansur",
        views: "27,548",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4", type: "video/mp4",  },
      },
      {
        id: 8,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "Waters Years",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Sonny",
        views: "27,548",
        time: "2 hours ago",
        date: new Date(2018, 3, 15, 10, 33, 30, 0),
        video: { src: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", type: "video/mp4",  },
      }]