export const Photos = [
    {
        id: 1,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Mansur",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://wallpapercave.com/wp/s6s5ywY.jpg"
    },
    {
        id: 2,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Mansur",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://images7.alphacoders.com/617/617268.jpg"
    },
    {
        id: 3,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Won hee lee",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://www.nationalgeographic.com/content/dam/animals/rights-exempt/best-of-animals-2018/photo-ark-parrots-endangered-bird-world-intelligence-3.adapt.1900.1.jpg"
    },
    {
        id: 4,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Won hee lee",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://www.redringtones.com/wp-content/uploads/2016/12/elephant-sound.jpg"
    },
    {
        id: 5,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Sonny",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://www.wallpapers13.com/wp-content/uploads/2016/06/Animal-kingdom-dwellers-of-the-jungle-Desktop-backgrounds-free-download-for-windows-915x515.jpg"
    },
    {
        id: 6,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Mansur",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://i.pinimg.com/originals/48/7f/43/487f43fc6a4ed87968a4735c953d3ad9.jpg"
    },
    {
        id: 15,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Mansur",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://cdn.britannica.com/37/154237-050-A76A506D/blue-peafowl-tail-Indian-peacock-courtship-displays.jpg"
    },
    {
        id: 16,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Mansur",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://i.pinimg.com/originals/41/63/6f/41636f7fb6a932332bf3427a3c4654c5.jpg"
    },   
    {
        id: 7,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Mansur",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://i.pinimg.com/originals/99/28/ac/9928acf99c509aceb23c64e66b99026d.jpg"
    },    
    {
        id: 8,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Mansur",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://wallpapercave.com/wp/s6s5ywY.jpg"
    },
    {
        id: 9,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Mansur",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://images7.alphacoders.com/617/617268.jpg"
    },
    {
        id: 10,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Won hee lee",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://www.nationalgeographic.com/content/dam/animals/rights-exempt/best-of-animals-2018/photo-ark-parrots-endangered-bird-world-intelligence-3.adapt.1900.1.jpg"
    },
    {
        id: 11,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Won hee lee",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://www.redringtones.com/wp-content/uploads/2016/12/elephant-sound.jpg"
    },
    {
        id: 12,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Sonny",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://www.wallpapers13.com/wp-content/uploads/2016/06/Animal-kingdom-dwellers-of-the-jungle-Desktop-backgrounds-free-download-for-windows-915x515.jpg"
    },
    {
        id: 13,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Mansur",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://i.pinimg.com/originals/48/7f/43/487f43fc6a4ed87968a4735c953d3ad9.jpg"
    }, 
    {
        id: 14,
        channelIcon: "",
        channelName:"Fowl Behold Saw",
        title: "lorem ipsum photos",
        desc: "Man's Sky: 21 Minutes of New Gameplay - IGN First",
        author: "Mansur",
        views: "27,548",
        comments: "5",
        time: "2 hours ago",
        date: new Date(2018, 11, 24, 10, 33, 30, 0),
        src:"https://cdn.britannica.com/37/154237-050-A76A506D/blue-peafowl-tail-Indian-peacock-courtship-displays.jpg"
    },    
  ];
  