//add language in abc order

export const MainTextEnglish = {
    ACCOUNT_TYPE: "account type",
    ACTION_TEXT: "Action",
    ACTIVATE_DEACTIVATE_POWER: "activate/deactivate members",
    ACTIVATE_TEXT: "activate",
    ADD_CHANNEL: "Add Channel",
    ALL_CHANNEL_MEMBER: "All Channel Members",
    ADD_FOLDER: "Add Folder",
    ADD_FREE_PERIOD: "would you like to add free trial period?",
    ADD_SUBSCRIPTION: "add subscription service?",
    ADD_TAGS: "Please, add tags with  sharp ex) #tv, #radio",
    ADD_TEXT: "ADD",
    ALL_EPICS: "All Epics",
    ALL_MEMBER: "All Members including guests",
    ALL_NOTEBOOKS: "All Notebooks",
    ALL_NOTES: "All Notes",
    ALL_PROJECTS: "All Projects",
    ALL_STORIES: "All Stories",
    APP_STORE: "App Store",
    ASSIGN_BLOG_MANAGER: "assign blog manager",
    AUDIO_TEXT: "audio",
    AUTHENTICATION_STATUS: "authentication",
    AWAY_TEXT: "Away",
    BLOG_PUBLIC: "Set the blog in public",
    BLOG_TAB: "Blog",
    BLOG_TEXT: "Blog",
    BLOG_THEME_BASIC: "basic",
    BLOG_THEME_CARDTYPE: "card type",
    BUDGET: "Budget",
    CALLING_TO: "Calling to",
    CANCEL_TEXT: "Cancel",
    CARD_VIEW: "Card View",
    CONFERENCE_CALL: "Conference Call",
    CONFERENCE: "Conference",
    CURRENT_CHANNEL: "current your channel",
    CHATTING_ROOM_TEXT: "Chatting room",
    CHANGE_CHANNEL_PROFILE_NAME: "change your channel name",
    CURRENT_CHANNEL_URL: "current channel url",
    CHANNEL_MEMBER_TYPE: "member type",
    CHANGE_PROFILE_NAME: "change profile name",
    CHANNEL_ROOM_LIMIT: "up to 5 rooms",
    CHANNEL_ROOM_UNLIMIT: "unlimited",
    CHANNEL_TAB: "Channels",
    CHANNEL_TEXT: "Channels",
    CHANNEL_HOME: "Channel Home",
    CLOSE_TEXT: "Close",
    CONFIRM_TEXT: "Confirm",
    CONTENTS_TEXT: "Contents",
    CREATE_A_CLASSROOM: "Create a classroom",
    CREATED_BY: "Created By",
    CREATE_EPIC: "Create A New Epic",
    CREATE_FOLDER: "Create A Folder",
    CREATE_GROUP: "Create A Group",
    CREATE_NEW: "Create New",
    CREATE_NOTE: "Create A New Note",
    CREATE_NOTEBOOK: "Create A New Notebook",
    CREATE_NEW_NOTIFICATION: "Create New Notification",
    CREATE_PROJECT: "Create A New Project",
    CREATE_ROOM: "Create A Room",
    CREATE_STORY: "Create A New Story",
    DATE_TEXT: "Date",
    DEACTIVATE_TEXT: "deactivate",
    DEACTIVATED_TEXT: "deactivated",
    DELETE_EPIC: "Delete Epic",
    DELETE_PROJECT: "Delete Project",
    DELETE_STORY: "Delete Story",
    DELETE_NOTIFICATION: "Delete notification",
    DISABLE_TEXT: "disable",
    DELETE_FOREVER_TEXT: "Delete Forever",
    DELETED_DATE: "Deleted",
    DISPLAY_BOOKMARK: "Display Bookmark",
    EVENT_TEXT: "Event",
    EVERY_ONE: "Every one",
    SOCIAL_MEDIAL: "Social Media",
    DOWNLOADS: "Download",
    DRAG_ICONS: "Please, drag icons to upload contents",
    DUE_DATE: "Due Date",
    EMAIL_MOBILE: "Both Email & Mobile",
    EMAIL_ONLY: "Email Only",
    EPIC_NAME: "Epic Name",
    FACEBOOK_BOARDS: "Facebook Boards",
    FILE_CHANNELS_ONLY: "File channels only",
    FILES_TAB: "Files",
    FILES_TEXT: "Files",
    FORMATTING_TEXT: "Formatting",
    FREE_PLAN_EXPLAIN: "You are on the FREE plan, you can click",
    FILE_STORAGE_USED: "total storage used",
    FROM_TEXT: "From",
    FILE_TYPE_TEXT: "File Type",
    GENERAL_PROJECT: "General Project",
    GO_LIVE: "Go Live",
    IMPORTANT_TEXT: "Important",
    INCREASE_ROOM_LIMIT: "increase the limit of channel room",
    INSERT_TEXT: "Insert",
    INVITED_TEXT: "Invited",
    INVITE_SNS: "invite all your SNS friends",
    INVITE_NEW_MEMBERS: "invite new members",
    INVITE_PEOPLE: "Invite people...",
    INVITE_PEOPLE_TO: "Invite people to",
    JOIN_TEXT: "Join",
    LAST_UPDATE: "Last Update",
    LIVE_TEXT: "Live Mode",
    LECTURE_MODE: "Lecture Mode",
    LOCKNUNLOCK_TEXT: "Lock/Unlock",
    MEETING_TEXT: "Meeting",
    MEMBER_NOT_FOUND: "Member Not Found.",
    MEMBERS_TAB: "Members",
    MESSAGE_TOTAL: "total messages",
    MISSING_PREVIEW: "Missing Preview?",
    MOBILE_ONLY: "Mobile Only",
    MODIFY_EPIC: "Modify Epic",
    MODIFY_PROJECT: "Modify Project",
    MODIFY_STORY: "Modify Story",
    MODIFY_NOTIFICATION: "Modify Notification",
    MONETIZE_TAB: "Monetize",
    MONETIZE_FILES: "monetize your files?",
    MONETIZE_VIDEO: "monetize your video?",
    MONETIZE_BLOG: "monetize your blog?",
    MONETIZE_MUSIC: "monetize your music?",
    MONITOR_SHARE: "Monitor Sharing",
    MONTH_JAN_TEXT: "JAN",
    MONTH_FEB_TEXT: "FEB",
    MONTH_MAR_TEXT: "MAR",
    MONTH_APR_TEXT: "APR",
    MONTH_MAY_TEXT: "MAY",
    MONTH_JUN_TEXT: "JUN",
    MONTH_JUL_TEXT: "JUL",
    MONTH_AUG_TEXT: "AUG",
    MONTH_SEP_TEXT: "SEP",
    MONTH_OCT_TEXT: "OCT",
    MONTH_NOV_TEXT: "NOV",
    MONTH_DEC_TEXT: "DEC",
    MORE_ACTIONS: "More Actions",
    MORE_OPTIONS: "More Options",
    MY_SCHEDULE: "My Schedule",
    NEW_PROJECT: "New Project",
    NEW_PROJECT: "New Project",
    NEW_STORY: "New Story",
    NEW_NOTE: "New Note",
    NO_CHANGE_CHANNEL_NAME: "no, thanks!",
    NO_CHANGE_PROFILE_NAME: "no, thanks!",
    NO_CHANNEL_MANAGER_APPOINTMENT: "no, thanks!",
    NO_DATA_TO_DISPLAY: "No data to display",
    NO_OF_EPICS: "No.of Epics",
    NO_OF_STORY: "No. of Story",
    NORMAL_TEXT: "General",
    NO_MONETIZE: "no, thanks!",
    NOTEBOOK_CATEGORY: "Notebook Category",
    NOTEBOOK_RENAME: "Rename Notebook",
    NOTEBOOK_DELETE: "Delete Notebook",
    NOTEBOOK_TITLE: "Notebook Title",
    NOTEBOOK_TEXT: "Notebook",
    NOTE_TITLE: "Note Title",
    NOTIFY_TITLE: "Title",
    NOTIFICATIONS: "Notifications",
    NOTIFY_MEMBERS: "Notify Members",
    REPLY: "Reply",
    NOTIFICATION_NO: "No",
    NOTIFY_CHANNEL_MEMBERS: "notify channel members",
    NO_THANKS_ADD_CHANNEL: "no, thanks!",
    NO_INVITE_SNS: "no, thanks!",
    NO_PUSH_SETTING: "no, thanks!",
    NUMBER_TEXT_SHORT: "No",
    ONLINE_TEXT: "Online",
    OPEN_TO_PUBLIC: "Open to public",
    ON_TEXT: "on",
    OFF_TEXT: "off",
    PAID_SUBSCRIBER_TEXT: "Paid Subscribers",
    PAID_SUBSCRIBER_ONLY: "only to paid subscribers",
    PERSON_IN_CHARGE: "Person In Charge",
    PLAN_BASIC: "basic",
    PLAN_STANDARD: "standard",
    PLAN_PREMIUM: "premium",
    PLAN_ENTERPRISE: "enterprise",
    PLEASE_SELECT_NOTE: "Please, select note from the list to view and edit note data.",
    PRIVATE_TEXT: "private",
    PROJECT_TYPE: "Project Type",
    PROJECT_TAB: "Project",
    PROGRESS: "Progress",
    PROJECT_NAME: "Project Name",
    PROJECT_HOME: "Project Home",
    PROJECT_OWNER: "Project Owner",
    PROJECT_SHORT_DESCRIPTION: "Project Short Description",
    PUSH_CALL_SETTING: "Push call setting",
    REPLY_ON_YOUR_WRITING: "reply on your writing",
    REQUESTED_TO: "Requested To",
    REQUEST_TO_APPROVE: "Request to approve",
    RECENT_TEXT: "Recent",
    RESUME_TEXT: "Resume",
    RECORD_TEXT: "Recode",
    SAVE_TEXT: "Save",
    SELECT_PARTICIPANTS: "Select Participatns",
    SELECT_PERSON_IN_CHARGE: "Select a person in Charge",
    SELECT_YOUR_PLAN: "select your plan",
    SELECT_YOUR_LANGUAGE: "select language",
    SELECT_YOUR_THEME: "select theme",
    SET_BLOG_THEME: "set channel blog theme",
    SHARE_TEXT: "Share",
    SHARE_NOTEBOOK: "Share Notebook",
    SHARE_NOTE: "Share Note",
    EDIT_NOTE: "Edit Note",
    DELETE_NOTE: "Delete Note",
    SHARE_PROJECT: "Share Project",
    SHARE_EPIC: "Share Epic",
    SHARE_MONITOR_DESCRIPTION: "Copy the below code to invite a guest or select a member.",
    SHARE_STORY: "Share Story",
    SHARE_NOTIFICATION: "Share Notification",
    SUBSCRIBED_CHANNELS_ONLY: "Subscribed channels only",
    SUBSCRIBED_MEMBERS_ONLY: "Subscribed members only",
    STARRED_MEMBER_ONLY: "Starred member only",
    STORIES_TEXT: "The Latest Stories",
    SUBSCRIBER_BIRTHDAY: "subscriber's birthday",
    SUBSCRIBER_ONLY: "only to subscribers",
    SUBSCRIBERS_TEXT: "Subscribers",
    SUBSCRIBED_USER: "Subscribed User",
    SAVE_TEXT: "Save",
    SEND_TEXT: "Send",
    SETTING_TAB: "Setting",
    SETTINGS_DOT: "Settings...",
    SHARED_WITH: "Shared With",
    SIGN_OUT_CURRENT_CHANNEL: "Unsubscribe the current channel",
    STATE_TEXT: "State",
    STORY_NAME: "Story Name",
    TABLE_VIEW: "Table View",
    TITLE_TEXT: "Title",
    TO_TEXT: "To",
    TOTAL_NOTE: "Total Note",
    TOTAL_PAID_SUBSCRIBER: "total paid subscribers",
    TOTAL_SUBSCRIBER: "total subscribers",
    TOTAL_DAILY_VISITORS: "daily visitors",
    TRASH: "Trash",
    THREAD: "Thread",
    TWO_STEP_PLAN_UP: "to utilize two step authentication, you need to upgrade the plan",
    TWO_STEP_TEXT: "two step authentication",
    TYPE_TEXT: "Type",
    UPGRATE_MEMBER: "button to upgrade your membership",
    USER_PROFILE_NAME_TITLE: "profile name",
    USER_STATUS: "user status",
    VIDEO_TEXT: "Video",
    VIDEO_CHANNELS_ONLY: "video channels only",
    VIDEO_MONITOR: "video monitor",
    VIDEO_CONFERENCE: "video conference",
    VIEW_PROJECT: "View project",
    VIEW_EPICS: "View epics",
    VIEW_SCHEDULE: "View Schedule",
    VIEW_STORY: "View story",
    YES_INVITE_SNS: "yes, please!",
    YES_CHANGE_PROFILE_NAME: "yes, please!",
    YES_CHANGE_CHANNEL_NAME: "yes, please!",
    YES_CHANNEL_MANAGER_APPOINTMENT: "yes, please!",
    YES_MONETIZE: "yes, please!",
    YES_PUSH_SETTING: "yes, please!",
    YES_THANKS_ADD_CHANNEL: "yes, please!",
    YOUTUBE_CAMPAIGN: "Youtube Campaign",
    UNLOCK_OPEN_TO_SNS: "Unlock and post this SNS",
    UPDATED_TEXT: "Updated",
    UPGRADE_TO_STANDARD: "upgrade to standard plan",
    USER_ADMIN_TAB: "Admin",
}

export const MainTextKorean = {
    ACCOUNT_TYPE: "계정타입",
    ACTION_TEXT: "설정",
    ACTIVATE_DEACTIVATE_POWER: "멤버 비/활성화",
    ACTIVATE_TEXT: "활성화",
    ADD_CHANNEL: "채널 추가",
    ADD_FOLDER: "폴더 추가",
    ADD_FREE_PERIOD: "무료 구독기간을 설정하시겠습니까?",
    ADD_SUBSCRIPTION: "정기 구독을 서비스를 하시겠습니까?",
    ADD_TAGS: "태그를 추가하세요! 예) #tv, #radio",
    ADD_TEXT: "추가",
    ALL_MEMBER: "게스트를 포함한 모든 멤버",
    ALL_CHANNEL_MEMBER: "모든 채널 멤버",
    ALL_EPICS: "전체 에피소드",
    ALL_NOTEBOOKS: "전체 노트북",
    ALL_NOTES: "전체 노트",
    ALL_PROJECTS: "전체 프로젝트",
    ALL_STORIES: "전체 스토리",
    APP_STORE: "앱스토어",
    ASSIGN_BLOG_MANAGER: "블로그 매니저 지명",
    AUDIO_TEXT: "오디오",
    AUTHENTICATION_STATUS: "씨큐리티",
    AWAY_TEXT: "자리비움",
    BUDGET: "예산",
    BLOG_PUBLIC: "블로그 공개",
    BLOG_TAB: "블로그",
    BLOG_TEXT: "블로그",
    BLOG_THEME_BASIC: "블로그 타입",
    BLOG_THEME_CARDTYPE: "카드 타입",
    CALLING_TO: "님에게 연결중입니다",
    CANCEL_TEXT: "취소",
    CARD_VIEW: "카드 뷰",
    CONFERENCE_CALL: "컨퍼런스 콜",
    CONFERENCE: "컨퍼런스",
    CURRENT_CHANNEL: "현재 채널 정보",
    CHATTING_ROOM_TEXT: "대화방 ",
    CHANGE_CHANNEL_PROFILE_NAME: "채널명 변경",
    CHANNEL_MEMBER_TYPE: "멤버 타입",
    CHANGE_PROFILE_NAME: "사용자명 변경",
    CHANNEL_ROOM_LIMIT: "최대 5개",
    CHANNEL_ROOM_UNLIMIT: "무제한",
    CHANNEL_TAB: "채널",
    CHANNEL_TEXT: "채널",
    CHANNEL_HOME: "채널 홈",
    CONFIRM_TEXT: "확인",
    CLOSE_TEXT: "닫기",
    CONTENTS_TEXT: "내용",
    CREATED_BY: "작성자",
    CREATE_EPIC: "신규 에피소드 만들기",
    CREATE_FOLDER: "폴더 생성",
    CREATE_GROUP: "그룹생성",
    CREATE_NEW: "새로작성",
    CREATE_NOTE: "새 노트 작성",
    CREATE_NOTEBOOK: "새 노트북",
    CREATE_NEW_NOTIFICATION: "신규 공지작성",
    CREATE_PROJECT: "새로운 프로젝트 만들기",
    CREATE_ROOM: "새로운 방 생성하기",
    CREATE_A_CLASSROOM: "클라스룸 생성하기",
    CREATE_STORY: "신규 스토리 만들기 ",
    CURRENT_CHANNEL_URL: "채널 사이트주소",
    DATE_TEXT: "날짜",
    DEACTIVATE_TEXT: "비활성화",
    DEACTIVATED_TEXT: "비활성화",
    DELETE_EPIC: "에피소드 삭제",
    DELETED_DATE: "삭제일",
    DELETE_PROJECT: "프로젝트 삭제",
    DELETE_STORY: "스토리 삭제",
    DELETE_FOREVER_TEXT: "영구 삭제",
    DELETE_NOTIFICATION: "공지 삭제",
    DISPLAY_BOOKMARK: "북마크 표시",
    SOCIAL_MEDIAL: "소셜 미디어",
    DISABLE_TEXT: "사용하지 않음",
    DOWNLOADS: "다운로드",
    DRAG_ICONS: "아이콘을 여기로 끌어오세요!",
    DUE_DATE: "마감일",
    EMAIL_MOBILE: "이메일과 핸드폰 모두 통보",
    EMAIL_ONLY: "이메일로만 통보",
    EPIC_NAME: "에피소드 제목",
    EVENT_TEXT: "이벤트",
    EVERY_ONE: "모두",
    FACEBOOK_BOARDS: "Facebook 보드",
    FILE_CHANNELS_ONLY: "파일 전문 채널만 표시",
    FILES_TAB: "파일",
    FILES_TEXT: "파일",
    FILE_TYPE_TEXT: "파일 타입",
    FORMATTING_TEXT: "추가 기능",
    FREE_PLAN_EXPLAIN: "현재 무료버전을 이용중입니다.",
    FROM_TEXT: "발신",
    FILE_STORAGE_USED: "파일 스토리지 사용량",
    GENERAL_PROJECT: "일반 프로젝트",
    GO_LIVE: "방송하기",
    IMPORTANT_TEXT: "중요",
    INCREASE_ROOM_LIMIT: "채널룸 증설",
    INSERT_TEXT: "삽입",
    INVITED_TEXT: "초대 회원",
    INVITE_SNS: "SNS의 친구를 초대합니다.",
    INVITE_NEW_MEMBERS: "신규 멤버 초대",
    INVITE_PEOPLE_TO: "채널로 초대",
    INVITE_PEOPLE: "신규 초대",
    JOIN_TEXT: "참여",
    LAST_UPDATE: "최근 업데이트",
    LIVE_TEXT: "라이브 모드",
    LECTURE_MODE: "강의 모드",
    LOCKNUNLOCK_TEXT: "잠금/열림",
    MEETING_TEXT: "회의중",
    MEMBER_NOT_FOUND: "멤버를 찾을수 없습니다.",
    MEMBERS_TAB: "멤버",
    MESSAGE_TOTAL: "전체 메세지",
    MISSING_PREVIEW: "프리뷰가 안보이세요?",
    MOBILE_ONLY: "핸드폰으로만 통보",
    MODIFY_EPIC: "에피소드 수정",
    MODIFY_STORY: "스토리 수정",
    MODIFY_PROJECT: "프로젝트 수정",
    MODIFY_NOTIFICATION: "공지 수정",
    MONETIZE_TAB: "비즈니스",
    MONETIZE_FILES: "파일을 판매하시겠습니까?",
    MONETIZE_VIDEO: "동영상을 판매하시겠습니까?",
    MONETIZE_BLOG: "블로그에 광고를 삽입하시겠습니까?",
    MONETIZE_MUSIC: "음악을 판매하시겠습니까?",
    MONITOR_SHARE: "모니터 공유",
    MONTH_JAN_TEXT: "1월",
    MONTH_FEB_TEXT: "2월",
    MONTH_MAR_TEXT: "3월",
    MONTH_APR_TEXT: "4월",
    MONTH_MAY_TEXT: "5월",
    MONTH_JUN_TEXT: "6월",
    MONTH_JUL_TEXT: "7월",
    MONTH_AUG_TEXT: "8월",
    MONTH_SEP_TEXT: "9월",
    MONTH_OCT_TEXT: "10월",
    MONTH_NOV_TEXT: "11월",
    MONTH_DEC_TEXT: "12월",
    MORE_ACTIONS: "메뉴",
    MORE_OPTIONS: "추가 옵션",
    MY_SCHEDULE: "내 일정",
    NEW_NOTE: "노트작성",
    NEW_PROJECT: "신규 프로젝트",
    NEW_PROJECT: "신규 프로젝트",
    NEW_STORY: "신규 스토리",
    NO_CHANGE_CHANNEL_NAME: "아니요 그대로 유지합니다.",
    NO_CHANGE_PROFILE_NAME: "아니요, 변경하지 않습니다.",
    NO_CHANNEL_MANAGER_APPOINTMENT: "아니요, 임명하지 않습니다.",
    NO_DATA_TO_DISPLAY: "데이터가 존재하지 않습니다",
    NO_MONETIZE: "아니요, 일반으로 사용합니다.",
    NO_OF_EPICS: "에피소드",
    NO_OF_STORY: "스토리",
    NORMAL_TEXT: "일반",
    NOTEBOOK_CATEGORY: "노트북 카테고리",
    NOTEBOOK_TITLE: "노트북 제목",
    NOTEBOOK_TEXT: "노트북",
    NOTEBOOK_RENAME: "이름변경",
    NOTEBOOK_DELETE: "노트북 삭제",
    NOTE_TITLE: "노트 제목",
    NOTIFICATIONS: "공지 사항",
    NOTIFY_TITLE: "공지 제목",
    NOTIFY_MEMBERS: "공지 작성",
    REPLY: "답변",
    NOTIFICATION_NO: "No",
    NOTIFY_CHANNEL_MEMBERS: "공지사항 발송",
    NO_THANKS_ADD_CHANNEL: "아니요, 채널을 추가하지 않습니다.",
    NO_INVITE_SNS: "아니요, 초대하지 않습니다.",
    NO_PUSH_SETTING: "아니요, 설정하지 않습니다.",
    NUMBER_TEXT_SHORT: "번호",
    ONLINE_TEXT: "온라인",
    ON_TEXT: "사용",
    OFF_TEXT: "사용하지 않음",
    OPEN_TO_PUBLIC: "외부로 공개",
    PAID_SUBSCRIBER_TEXT: "유료 구독자",
    PAID_SUBSCRIBER_ONLY: "유료 구독자에게만 공개",
    PERSON_IN_CHARGE: "담당자",
    PLAN_BASIC: "기본형",
    PLAN_STANDARD: "스탠다드",
    PLAN_PREMIUM: "프리미엄",
    PLAN_ENTERPRISE: "기업 전용",
    PLEASE_SELECT_NOTE: "좌측 패널의 노트를 선택하세요!",
    PRIVATE_TEXT: "공개하지 않음",
    PROGRESS: "진행율",
    PROJECT_NAME: "프로젝트 명",
    PROJECT_HOME: "프로젝트 홈",
    PROJECT_SHORT_DESCRIPTION: "프로젝트 간단 설명",
    PROJECT_TAB: "프로젝트",
    PROJECT_TYPE: "프로젝트 타입",
    PROJECT_OWNER: "개시자",
    PUSH_CALL_SETTING: "PUSH 통보 세팅",
    REPLY_ON_YOUR_WRITING: "답변이 달릴경우",
    REQUESTED_TO: "수신인",
    REQUEST_TO_APPROVE: "승인 요청",
    RECENT_TEXT: "최근",
    RECORD_TEXT: "녹화",
    RESUME_TEXT: "복구",
    SAVE_TEXT: "저장",
    SELECT_PARTICIPANTS: "참여자를 선택하세요.",
    SELECT_PERSON_IN_CHARGE: "담당자 선정.",
    SELECT_YOUR_PLAN: "플랜을 선택하세요.",
    SELECT_YOUR_LANGUAGE: "언어를 선택하세요.",
    SELECT_YOUR_THEME: "테마를 선택하세요.",
    SET_BLOG_THEME: "블로그 테마 변경",
    SHARE_MONITOR_DESCRIPTION: "아래 코드를 복사하여 외부인을 초대하거나 아래 리스트에서 공유자를 선택하세요.",
    SHARED_WITH: "공유",
    SHARE_EPIC: "에픽 공유",
    SHARE_PROJECT: "프로젝트 공유",
    SHARE_STORY: "이야기 공유",
    SHARE_TEXT: "공유",
    SHARE_NOTIFICATION: "공유 알림",
    SHARE_NOTEBOOK: "노트북 공유",
    EDIT_NOTE: "메모 수정",
    DELETE_NOTE: "메모 삭제",
    SHARE_NOTE: "노트 공유",
    SIGN_OUT_CURRENT_CHANNEL: "현재 채널 구독취소",
    SUBSCRIBED_CHANNELS_ONLY: "구독 채널만 표시",
    SUBSCRIBED_MEMBERS_ONLY: "구독자만 표시",
    STARRED_MEMBER_ONLY: "별체크 멤버만 표시",
    SUBSCRIBER_BIRTHDAY: "구독자의 생일",
    SUBSCRIBER_ONLY: "구독자에게만 공개",
    SUBSCRIBERS_TEXT: "구독자에게만",
    SUBSCRIBED_USER: "구독자",
    SAVE_TEXT: "저장",
    SEND_TEXT: "발송",
    SETTING_TAB: "기본 설정",
    SETTINGS_DOT: "기초 설정...",
    STORIES_TEXT: "최근 스토리 목록",
    STORY_NAME: "스토리 제목",
    STATE_TEXT: "상태",
    TABLE_VIEW: "테이블 보기",
    TITLE_TEXT: "제목",
    TOTAL_PAID_SUBSCRIBER: "유료 구독자수",
    TO_TEXT: "수신",
    TOTAL_SUBSCRIBER: "일반 구독자수",
    TOTAL_DAILY_VISITORS: "일일 방문객수",
    TRASH: "휴지통",
    THREAD: "쓰레드",
    TYPE_TEXT: "공지타입",
    TWO_STEP_PLAN_UP: "2중 보안은 스탠다드 플랜부터 적용이 됩니다.",
    TWO_STEP_TEXT: "2중 보안 설정",
    UNLOCK_OPEN_TO_SNS: "등록된 소셜미디어에 공개",
    UPDATED_TEXT: "최근 업데이트",
    UPGRATE_MEMBER: "U버튼을 눌러 업그레이드하세요.",
    UPGRADE_TO_STANDARD: "upgrade to standard plan",
    USER_ADMIN_TAB: "관리자",
    USER_PROFILE_NAME_TITLE: "사용자명",
    USER_STATUS: "사용자 현황",
    VIDEO_MONITOR: "비디오",
    VIDEO_CHANNELS_ONLY: "비디오 채널만 표시",
    VIDEO_CONFERENCE: "비디오 컨퍼런스",
    VIDEO_TEXT: "비디오",
    VIEW_IN_GRAPH: "그래프로 보기",
    VIEW_EPICS: "에피소드",
    VIEW_SCHEDULE: "스케쥴 보기",
    VIEW_STORY: "스토리",
    YES_INVITE_SNS: "네, 초대합니다.",
    YES_CHANGE_CHANNEL_NAME: "네 변경하겠습니다.",
    YES_CHANGE_PROFILE_NAME: "네, 변경합니다.",
    YES_CHANNEL_MANAGER_APPOINTMENT: "네, 임명합니다.",
    YES_MONETIZE: "네, 상업화하겠습니다.",
    YES_PUSH_SETTING: "네, 설정합니다.",
    YES_THANKS_ADD_CHANNEL: "네, 채널을 추가하겠습니다.",
    YOUTUBE_CAMPAIGN: "유투브 캠페인",
}

export const MainTextJapanese = {
    ALL_NOTES: "すべてのメモ",
    SAVE_TEXT: "保存",
    FREE_PLAN_EXPLAIN: "현재 무료버전을 이용중입니다.U버튼을 눌러 업그레이드하세요.",
    UPGRATE_MEMBER: "",
    CURRENT_CHANNEL: "current your channel",
    CURRENT_CHANNEL_URL: "채널 사이트주소",
    ADD_CHANNEL: "add another channel",
    NO_THANKS_ADD_CHANNEL: "아니요",
    YES_THANKS_ADD_CHANNEL: "네",
    ADD_TEXT: "추가",
}
