export const testData = {
    dataContentDescription: {
        content: [
            {
                title: `Cast`,
                text: `Nathan Drake , Victor Sullivan , Sam Drake , Elena Fisher`,
            },
            {
                title: `Category`,
                text: `Gaming , PS4 Exclusive , Gameplay , 1080p`,
            },
            {
                title: `About`,
                text: `Three years after the events of Uncharted 3: Drake's Deception, Nathan Drake, now retired as a fortune hunter, has settled into a normal life with his wife Elena Fisher. His world is then turned upside down when his older brother Sam, long believed to be dead, suddenly reappears seeking Drake's help.`,
            },
        ],
        tags: [
            {
                title: "Tags",
                tags: [
                    {
                        link: "#",
                        tagName: "Uncharted 4",
                    },
                    {
                        link: "#",
                        tagName: "Playstation 4",
                    },
                    {
                        link: "#",
                        tagName: "Gameplay",
                    },
                    {
                        link: "#",
                        tagName: "1080",
                    },
                    {
                        link: "#",
                        tagName: "Pps4Share",
                    },
                    {
                        link: "#",
                        tagName: "+ 6",
                    },
                ],
            },
        ],
        release: {
            title: "Release Date",
            text: "2 Days ago",
        },
        license: {
            title: "License",
            text: "Standard",
        },
    },
    comments: [
        {
            id: 1,
            link: "#",
            avatar: "images/ava7.png",
            author: "BOWTZ pros",
            date: "1 week ago",
            text: `Really great story. You're doing a great job. Keep it up pal.`,
            likes: 245,
            dislikes: 1,
            replies: [
                {
                    id: 6,
                    link: "#",
                    avatar: "images/ava7.png",
                    author: "kingPIN",
                    date: "3 days ago",
                    text: `I was stuck too. then I started to shoot everything in Doom.`,
                    likes: 2,
                    dislikes: 11,
                },
                {
                    id: 7,
                    link: "#",
                    avatar: "images/ava7.png",
                    author: "Test test",
                    date: "4 days ago",
                    text: `Season 6: Event Promo`,
                    likes: 2,
                    dislikes: 11,
                },
                {
                    id: 8,
                    link: "#",
                    avatar: "images/ava7.png",
                    author: "kingPIN",
                    date: "5 days ago",
                    text: `3DS Games Of 2016 that blew our mind`,
                    likes: 1112,
                    dislikes: 11,
                },
            ],
            flag: true,
        },
        {
            id: 2,
            link: "#",
            avatar: "images/ava7.png",
            author: "Isleifna",
            date: "2 week ago",
            text: `Omg thank you so much, idk how I couldn't figure out that master trap`,
            likes: 324,
            dislikes: 0,
            replies: [],
        },
        {
            id: 100,
            link: "#",
            avatar: "images/ava7.png",
            author: "BOWTZ pros",
            date: "1 week ago",
            text: `Really great story. You're doing a great job. Keep it up pal.`,
            likes: 245,
            dislikes: 1,
            replies: [
                {
                    id: 10,
                    link: "#",
                    avatar: "images/ava7.png",
                    author: "kingPIN",
                    date: "5 days ago",
                    text: `I was stuck too. then I started to shoot everything in Doom.`,
                    likes: 222,
                    dislikes: 11,
                },
                {
                    id: 11,
                    link: "#",
                    avatar: "images/ava7.png",
                    author: "Test test",
                    date: "9 days ago",
                    text: `Season 6: Event Promo`,
                    likes: 312,
                    dislikes: 11,
                },
            ],
        },
        {
            id: 4,
            link: "#",
            avatar: "images/ava7.png",
            author: "Isleifna",
            date: "2 week ago",
            text: `Omg thank you so much, idk how I couldn't figure out that master trap`,
            likes: 934,
            dislikes: 38,
            replies: [
                {
                    id: 5,
                    link: "#",
                    avatar: "images/ava7.png",
                    author: "kingPIN",
                    date: "3 days ago",
                    text: `I was stuck too. then I started to shoot everything in Doom.`,
                    likes: 23,
                    dislikes: 44,
                },
            ],
        },
    ],
    commentsForm: {
        link: "#",
        avatar: "images/ava7.png",
        countComments: 236,
    },
    playList: [
        {
            active: false,
            number: 1,
            imgUrl: "video1-4.png",
            time: "15:16",
            text: `Uncharted 4 A Thiefs End Walkthrough Part 1 ...`,
            views: "2,729,347",
            link: "#",
        },
        {
            active: false,
            number: 2,
            imgUrl: "video1-4.png",
            time: "43:53",
            text: `Uncharted 4 A Thiefs End Walkthrough Part 2 ...`,
            views: "1,347",
            link: "#",
        },
        {
            active: true,
            number: 3,
            imgUrl: "video1-4.png",
            time: "1:25:56",
            text: `Uncharted 4 A Thiefs End Walkthrough Part 3 ...`,
            views: "729,347",
            link: "#",
        },
        {
            active: false,
            number: 4,
            imgUrl: "video1-4.png",
            time: "2:16",
            text: `Uncharted 4 A Thiefs End Walkthrough Part 4 ...`,
            views: "29,347",
            link: "#",
        },
        {
            active: false,
            number: 5,
            imgUrl: "video1-5.png",
            time: "2:16",
            text: `Uncharted 5 A Thiefs End Walkthrough Part 4 ...`,
            views: "29,347",
            link: "#",
        },
    ],
    recomendedList: [
        {
            imgUrl: "video1-4.png",
            time: "5:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
        {
            imgUrl: "video1-4.png",
            time: "15:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
        {
            imgUrl: "video1-4.png",
            time: "15:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
        {
            imgUrl: "video1-4.png",
            time: "1:15:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
        {
            imgUrl: "video1-4.png",
            time: "15:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
        {
            imgUrl: "video1-4.png",
            time: "15:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
        {
            imgUrl: "video1-4.png",
            time: "15:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
        {
            imgUrl: "video1-4.png",
            time: "15:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
        {
            imgUrl: "video1-4.png",
            time: "15:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
        {
            imgUrl: "video1-4.png",
            time: "15:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
    ],
    upNext: [
        {
            imgUrl: "video1-4.png",
            time: "5:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
        {
            imgUrl: "video1-4.png",
            time: "15:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
        {
            imgUrl: "video1-4.png",
            time: "15:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
    ],
    similarVideos: [
        {
            imgUrl: "video1-4.png",
            time: "5:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
        {
            imgUrl: "video1-4.png",
            time: "15:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
        {
            imgUrl: "video1-4.png",
            time: "15:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
        {
            imgUrl: "video1-4.png",
            time: "1:15:16",
            text: `Cornfield Chase Outlast II Official Gameplay`,
            likes: "55%",
            views: "2,729,347",
            link: "#",
        },
    ],
}
